context_length: 48
dataloader_num_workers: 1
gradient_accumulation_steps: 1
learning_rate: 0.0002
log_steps: 1000
lr_scheduler_type: linear
max_missing_prop: 0.9
max_steps: 15000
min_past: 6
model_id: amazon/chronos-bolt-base
model_type: seq2seq
n_tokens: 2048
num_samples: 10
optim: adamw_torch_fused
output_dir: ./output/
per_device_train_batch_size: 32
prediction_length: 6
probability:
- 1.0
random_init: false
save_steps: 5000
seed: 42
shuffle_buffer_length: 25000
tf32: true
tie_embeddings: true
tokenizer_class: MeanScaleUniformBins
tokenizer_kwargs:
  high_limit: 4.0
  low_limit: -4.0
torch_compile: true
training_data_paths:
- /mnt/c/Users/Administrator/Documents/task/TSFMs/bolt/processed_data/lg_split2/train_data.arrow
use_eos_token: true
warmup_ratio: 0.1
